formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

output:
  file: README.md
  mode: inject
  template: |-
    [comment]: # (Begin TF Docs)
    {{ .Content }}
    [comment]: # (End TF Docs)

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: false
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
