formatter: "markdown" # this is required

version: ""

header-from: header.md
footer-from: footer.md


output:
  file: README.md
  mode: replace
  template: |-
    [comment]: # (Begin TF Docs)
    {{ .Content }}
    [comment]: # (End TF Docs)

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
