version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: tgremlin82/terraform_ansible_aws:1.0
    steps:
      - checkout
      - run:
          name: run AWS configure
          command: |
            aws configure --profile $CIRCLE_BRANCH set region $AWS_DEFAULT_REGION
            aws configure --profile $CIRCLE_BRANCH set access_key $AWS_ACCESS_KEY_ID
            aws configure --profile $CIRCLE_BRANCH set secret_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: install git and graphviz
          command: |
            apt update
            apt install git -y
            apt install graphviz -y
      - run:
          name: Export terraform environment variables
          command: |
            export TF_VAR_sqlusername=$sqlusername
            export TF_VAR_sqlpassword=$sqlpassword
            export TF_VAR_region=$AWS_DEFAULT_REGION
      - run:
          name: terraform init & plan
          command: |
            terraform fmt -recursive .
            terraform init -input=false
            terraform plan -out tfapply 
            terraform graph | dot -Tsvg > graph.svg
      - store_artifacts:
          path: /tmp/project/graph.svg
          destination: graph.svg   
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:   
    working_directory: /tmp/project  
    docker:
      - image: tgremlin82/terraform_ansible_aws:1.0
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy: 
    working_directory: /tmp/project
    docker:
      - image: tgremlin82/terraform_ansible_aws:1.0
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    working_directory: /tmp/project
    docker:
      - image: tgremlin82/terraform_ansible_aws:1.0
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
          